server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          # uri: file://C:/Users/palt1/Desktop/applications
          uri: https://github.com/minsuk1/spring-cloud-config

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh