server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          # uri: file://C:/Users/palt1/Desktop/applications
          uri: https://github.com/minsuk1/spring-cloud-config